export const POLLING_STATION_QUERY_STARTED = "POLLING_STATION_QUERY_STARTED"
export const POLLING_STATION_QUERY_FINISHED = "POLLING_STATION_QUERY_FINISHED"
export const POLLING_STATION_ZONE_CHANGED = "POLLING_STATION_ZONE_CHANGED"
export const POLLING_STATION_NUMBER_CHANGED = "POLLING_STATION_NUMBER_CHANGED"
